# This file was generated by GoReleaser. DO NOT EDIT.
cask "globetrotter" do
  os macos: "darwin", linux: "linux"

  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "188220b4c431de4c0769507fd05c67324893ad7bd692168f1705b89f65b2626b"
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cdcafd353917462d80216ca2b3f817d8305b69072a72ea29e82d39aacc9a86b"
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "909933a8b9a94b6930d7eb98c48e8857cd7df431047bf795468006cbf84571f3"
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c33b494a98564dbade5195caa3033db500254663a38adca3bcc0b85aece4079f"
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "globetrotter"
  desc "Polyglot, type-safe internationalization"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "globetrotter"

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/globetrotter"]
    end
  end

  # No zap stanza required

end
