# This file was generated by GoReleaser. DO NOT EDIT.
cask "globetrotter" do
  name "globetrotter"
  desc "Polyglot, type-safe internationalization"
  homepage ""
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "globetrotter"

  on_macos do
    on_intel do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_amd64.tar.gz"
      sha256 "676895a0b0740fb19df3a5f7b02e2f06e7904864f57fa674c6b6e47e82d71e84"
    end
    on_arm do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_arm64.tar.gz"
      sha256 "c463a4ec6e385e849f76d0270c6e5f2e137c484128d3d9c4074bff1d97030a7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_amd64.tar.gz"
      sha256 "6ba9ce3fea6f4f415e131a93dd94197d4afb9d669890ba66562a3758255ace58"
    end
    on_arm do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_arm64.tar.gz"
      sha256 "9d1578ac9a85564b840d4bd41615c69983fc8be5e309456f579355ecaa8d3d7d"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/globetrotter"]
    end
  end

  # No zap stanza required
end
