# This file was generated by GoReleaser. DO NOT EDIT.
cask "globetrotter" do
  name "globetrotter"
  desc "Polyglot, type-safe internationalization"
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "globetrotter"

  on_macos do
    on_intel do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_amd64.tar.gz"
      sha256 "57d0472bb29f35a0ab91c5b7fa9f626e7d7ab71516376f1d2a4943b62329d8af"
    end
    on_arm do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_darwin_arm64.tar.gz"
      sha256 "e435d8523748d19cc6951afc8a4998bedcd7cbe1d6b9ec11662a7e480f10ff0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_amd64.tar.gz"
      sha256 "294c816e5546cb763e2f98500cf1d8d03a50073b517bb650fb2900c59fd63c47"
    end
    on_arm do
      url "https://github.com/LuupSystems/globetrotter/releases/download/v#{version}/globetrotter_#{version}_linux_arm64.tar.gz"
      sha256 "3ddd2a5bb84042423de71a104afd628157dc772d099130cfa2e4d69a965c20c4"
    end
  end

  postflight do
    if OS.mac? && File.exist?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/globetrotter"]
    end
  end

  # No zap stanza required
end
