# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Globetrotter < Formula
  desc "Polyglot, type-safe internationalization"
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.4/globetrotter_0.0.4_darwin_amd64.tar.gz"
      sha256 "15886b98add3903df43d843c1007e8a060f285bd4795c3bd11e8ed3476f684dc"

      def install
        bin.install "globetrotter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.4/globetrotter_0.0.4_darwin_arm64.tar.gz"
      sha256 "1b7aad1d5624111c1a2884fb1dacee494e53eccd9886d2c08c53734ab492fe20"

      def install
        bin.install "globetrotter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.4/globetrotter_0.0.4_linux_amd64.tar.gz"
        sha256 "a5cff25048c950a8949e1d97c391ce544e42f5751edd86ff21965db305ee66ff"

        def install
          bin.install "globetrotter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.4/globetrotter_0.0.4_linux_arm64.tar.gz"
        sha256 "229b18b338c80a9810aa1277a0f57f06cd2ac09297ac070af58da03aa9a9cc4b"

        def install
          bin.install "globetrotter"
        end
      end
    end
  end
end
