# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Globetrotter < Formula
  desc "Polyglot, type-safe internationalization"
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.3/globetrotter_0.0.3_darwin_amd64.tar.gz"
      sha256 "2d1449d280b1aa6e6e6693a1ce74da6d4477755095c5b88f6a4d57c06697318c"

      def install
        bin.install "globetrotter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.3/globetrotter_0.0.3_darwin_arm64.tar.gz"
      sha256 "6d3b72213dd900ee4766bc08d8acce6e4307d407d82bc3c0e41780e1b0e67075"

      def install
        bin.install "globetrotter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.3/globetrotter_0.0.3_linux_amd64.tar.gz"
        sha256 "111d3191a4276d5dc1846d6542dabacac173915bedd8355573ce4b4a56d55351"

        def install
          bin.install "globetrotter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LuupSystems/globetrotter/releases/download/v0.0.3/globetrotter_0.0.3_linux_arm64.tar.gz"
        sha256 "ab2c1244b1890e629d4564e0747105ba1f53f72550e40d0812323a9a802fd6d3"

        def install
          bin.install "globetrotter"
        end
      end
    end
  end
end
